import { MigrationInterface, QueryRunner } from 'typeorm';

export class CREATEPRODUCT1736495430660 implements MigrationInterface {
  name = 'CREATEPRODUCT1736495430660';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`products_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`code\` varchar(255) NOT NULL, \`skuCode\` varchar(255) NOT NULL, \`price\` int NOT NULL, \`quantity\` int NOT NULL, \`thumbnail\` varchar(255) NULL,
                                         \`publicId\` varchar(255) NULL,
                                         \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_9d033b641cf74876b222242fb7\` (\`skuCode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(`
        INSERT INTO products_entity (id, name, description, code, skuCode, price, quantity, thumbnail)
            VALUES
        (1, 'Truffle Cups - Red', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'CETX', '881475814-X', 35, 59, 'http://dummyimage.com/251x117.png/ff4444/ffffff'),
        (2, 'Pumpkin - Seed', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'GHM', '244265129-7', 52, 65, 'http://dummyimage.com/144x277.png/ff4444/ffffff'),
        (3, 'Basil - Dry, Rubbed', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'PSCT', '614758019-1', 69, 21, 'http://dummyimage.com/205x298.png/5fa2dd/ffffff'),
        (4, 'Rice - Aborio', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'DYNT', '546596565-7', 30, 97, 'http://dummyimage.com/293x329.png/ff4444/ffffff'),
        (5, 'Pastry - Baked Cinnamon Stick', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'BWP', '830734003-9', 48, 82, 'http://dummyimage.com/214x359.png/5fa2dd/ffffff'),
        (6, 'Bagel - Plain', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'SHOO', '936874412-2', 90, 90, 'http://dummyimage.com/255x279.png/5fa2dd/ffffff'),
        (7, 'Grapes - Red', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'ERIE', '162351911-X', 26, 48, 'http://dummyimage.com/298x118.png/cc0000/ffffff'),
        (8, 'Mop Head - Cotton, 24 Oz', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 'BUD', '461717011-1', 12, 80, 'http://dummyimage.com/179x289.png/ff4444/ffffff'),
        (9, 'Trueblue - Blueberry Cranberry', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'SPSC', '377614714-8', 35, 66, 'http://dummyimage.com/168x398.png/cc0000/ffffff'),
        (10, 'Glass - Wine, Plastic, Clear 5 Oz', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'MZOR', '581510967-3', 45, 84, 'http://dummyimage.com/233x211.png/dddddd/000000'),
        (11, 'Lamb - Pieces, Diced', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'GDV^A', '263524246-1', 24, 34, 'http://dummyimage.com/286x161.png/5fa2dd/ffffff'),
        (12, 'Oil - Olive Bertolli', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'DAKT', '154803649-8', 73, 32, 'http://dummyimage.com/293x266.png/5fa2dd/ffffff'),
        (13, 'Kellogs Special K Cereal', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'NFBK', '629478247-3', 41, 84, 'http://dummyimage.com/259x301.png/5fa2dd/ffffff'),
        (14, 'Hickory Smoke, Liquid', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'LNN', '827089255-6', 10, 42, 'http://dummyimage.com/178x222.png/ff4444/ffffff'),
        (15, 'Sauce - Hp', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'EWZS', '281467913-9', 90, 79, 'http://dummyimage.com/227x108.png/dddddd/000000'),
        (16, 'Chocolate Eclairs', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'GDEN', '315218318-6', 61, 38, 'http://dummyimage.com/170x134.png/dddddd/000000'),
        (17, 'Cinnamon - Stick', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'COLL', '246859944-6', 22, 82, 'http://dummyimage.com/273x228.png/5fa2dd/ffffff'),
        (18, 'Tomato Paste', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'NATI', '856545054-6', 98, 15, 'http://dummyimage.com/210x115.png/5fa2dd/ffffff'),
        (19, 'Tea - Jasmin Green', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'PAYX', '008457118-7', 63, 76, 'http://dummyimage.com/185x148.png/cc0000/ffffff'),
        (20, 'Sauce - Soya, Light', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'XOXO', '875750560-8', 45, 12, 'http://dummyimage.com/276x379.png/5fa2dd/ffffff'),
        (21, 'Kellogs Special K Cereal', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'RXN', '379328346-1', 76, 38, 'http://dummyimage.com/253x155.png/dddddd/000000'),
        (22, 'Salmon Steak - Cohoe 6 Oz', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'OMC', '892917764-6', 10, 14, 'http://dummyimage.com/126x149.png/5fa2dd/ffffff'),
        (23, 'Sauce - Hoisin', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 'INOD', '379739497-7', 2, 13, 'http://dummyimage.com/123x364.png/5fa2dd/ffffff'),
        (24, 'Mustard - Dry, Powder', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'HGSH', '774556366-6', 11, 18, 'http://dummyimage.com/247x274.png/dddddd/000000'),
        (25, 'Wine - White, Ej Gallo', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'BRKS', '785293286-X', 9, 72, 'http://dummyimage.com/246x316.png/ff4444/ffffff'),
        (26, 'Nantuket Peach Orange', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'SGLB', '720089976-3', 39, 81, 'http://dummyimage.com/265x173.png/ff4444/ffffff'),
        (27, 'Sauce - Hoisin', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'PSA^W', '515156960-0', 8, 52, 'http://dummyimage.com/264x270.png/cc0000/ffffff'),
        (28, 'Lemonade - Island Tea, 591 Ml', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'RBS^L', '424267891-6', 62, 77, 'http://dummyimage.com/131x223.png/cc0000/ffffff'),
        (29, 'Contreau', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'CPG', '130511210-5', 96, 16, 'http://dummyimage.com/213x266.png/ff4444/ffffff'),
        (30, 'Pear - Packum', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'MBI', '890070662-4', 14, 63, 'http://dummyimage.com/299x338.png/dddddd/000000')
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX \`IDX_9d033b641cf74876b222242fb7\` ON \`products_entity\``,
    );
    await queryRunner.query(`DROP TABLE \`products_entity\``);
  }
}
